language: rust

# before_cache: |
#   if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
#     cargo install cargo-tarpaulin -f
#   fi

before_cache: |
    bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)

cache: cargo

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

script:
- cargo clean
- cargo build
- cargo test

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    # Uncomment the following line for coveralls.io
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

    # Uncomment the following two lines create and upload a report for codecov.io
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
