language: rust

cache: cargo

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
    cargo install cargo-update
    cargo install-update --all
  fi

before_cache:
    - rm -rf /home/travis/.cargo/registry


rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

script:
- cargo clean
- cargo build
- cargo test

after_success: |
  # this does require a -Z flag for Doctests, which is unstable!
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin --out Xml --run-types Tests Doctests
    bash <(curl -s https://codecov.io/bash)
  fi
